services:
    cwd_fancygrid.grid.factory:
        class: Cwd\FancyGridBundle\Grid\GridFactory
        public: true
        arguments:
            - "@translator"
            - "@doctrine"
            - "@twig"

    cwd_fancygrid.twig_extension.grid:
        class: Cwd\FancyGridBundle\Twig\FancyGridExtension
        arguments:
            - "@router"
            - "%cwd.fancygrid.config%"
        public: false
        tags:
            - { name: twig.extension }
